global:
  redis:
    password: ""

auth:
  ## @param auth.enabled Enable password authentication
  ##
  enabled: true
  ## @param auth.password Redis&reg; password
  ## Defaults to a random 10-character alphanumeric string if not set
  ##
  password: ""
metrics:
  ## @param metrics.enabled Start a sidecar prometheus exporter to expose Redis&reg; metrics
  ##
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "monitoring"
master:
  persistence:
    sizeLimit: 11Gi
    size: 10Gi